apiVersion: v1
kind: Service
metadata:
  name: lms-exam
  namespace: lms-ns
  labels:
    app: lms-exam
spec:
  selector:
    app: lms-exam
  type: NodePort
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-exam
  namespace: lms-ns
  labels:
    app: lms-exam
spec:
  selector:
    matchLabels:
      app: lms-exam
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lms-exam
    spec:
      containers:
      - name: lms-exam
        image: xxxxxxxxxxxxx
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: "xxxxx"
        - name: DB_DATABASE
          value: "xxxxxx"
        - name: DB_USERNAME
          value: "xxxxxxx"
        - name: DB_PASSWORD
          value: "xxxxxxx"
        ports:
        - containerPort: 80
          protocol: TCP
          name: lms-exam
      imagePullSecrets:
        - name: xxxxxxx