apiVersion: v1
kind: Service
metadata:
  labels:
    app: lms-web
    tier: frontend
  name: lms-web
  namespace: lms-ns
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: lms-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lms-web
  name: lms-web
  namespace: lms-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-web
  template:
    metadata:
      labels:
        app: lms-web
        tier: frontend
    spec:
      containers:
      - image: xxxxxxxxxxxxxxxxxx
        imagePullPolicy: Always
        name: lms-web
        env:
        - name: API_URL_PROD
          value: xxxxxxxxxxxxxxxxxx
        - name: API_URL
          value: xxxxxxxxxxxxxxxxxx
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: xxxxxxxxxxxxxxxxxx
      restartPolicy: Always