apiVersion: v1
kind: Service
metadata:
  name: lms-back
  namespace: lms-ns
  labels:
    app: lms-back
spec:
  selector:
    app: lms-back
    tier: backend
  type: NodePort
  ports:
    - port: 4040
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-back
  namespace: lms-ns
  labels:
    app: lms-back
spec:
  selector:
    matchLabels:
      app: lms-back
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lms-back
        tier: backend
    spec:
      containers:
      - image: xxxxxxxxxxxxxxxxxx
        imagePullPolicy: Always
        name: lms-back
        env:
        - name: BASE_URL_PROD
          value: "xxxxxxxxxxxxxxxxxx"
        - name: DB_HOST_PROD
          value: "xxxxxxxxxxxxxxxxxx"
        - name: DB_DIALECT_PROD
          value: "mysql"
        - name: DB_PORT_PROD
          value: "3306"
        - name: DB_USERNAME_PROD
          value: "xxxxxxxxxxxxxxxxxx"
        - name: DB_PASSWORD_PROD
          value: "xxxxxxxxxxxxxxxxxx"
        - name: DB_DATABASE_PROD
          value: "xxxxxxxxxxxxxxxxxx"
        ports:
        - containerPort: 4040
          protocol: TCP
          name: lms-back
      imagePullSecrets:
        - name: xxxxxxxxxxxxxxxxxx