kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  namespace: coupon-ns
  labels:
    app: redis
    service: coupon-back
    tier: caching
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.5-alpine
          ports:
            - name: port
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: coupon-ns
  labels:
    app: redis
    service: coupon-back
    tier: caching
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster